[package]
name = "bsec-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bsec = { version = "0.3.1", features = ["test-support"] }
nb = "1.0.0"
